name: flavor_core
version: 1.0.0+1
publish_to: none
description: A flavored flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  jwt_decoder: ^2.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

import_sorter:
  emojis: true
  comments: true
