name: {{project_name.snakeCase()}}
version: 1.0.0+1
publish_to: none
description: {{description}}
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  assets_gen: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

import_sorter:
  emojis: true
  comments: true
